name: libinterval
description: A mathematical interval implementation
version: 0.1.0
author: Eric Budai <eric_budai@hotmail.com>
homepage: https://github.com/ebudai/libinterval

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  quiver: ^2.0.3

dev_dependencies:
  test: any
  #test_coverage: ^0.3.0
