name: libinterval
description: A mathematical interval implementation with unbounded, closed, and open intervals, with standard operations (union, difference, intersection, symmetric difference)
version: 0.1.4
author: Eric Budai <eric_budai@hotmail.com>
homepage: https://github.com/ebudai/libinterval

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  quiver: ^2.0.3

dev_dependencies:
  test: any
  #test_coverage: ^0.3.0
